import {
  FaAws,
  FaDigitalOcean,
  FaDocker,
  FaGithub,
  FaJava,
  FaNodeJs,
  FaReact,
} from 'react-icons/fa6';
import {
  SiAdobeillustrator,
  SiAngular,
  SiC,
  SiFigma,
  SiJavascript,
  SiLinux,
  SiMicrosoftazure,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNginx,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiRedux,
  SiShadcnui,
  SiSpringboot,
  SiTailwindcss,
  SiTypescript,
} from 'react-icons/si';

import { BsGit } from 'react-icons/bs';
import { TSkill } from '@/types/skills.types';
import { TbBrandNextjs } from 'react-icons/tb';

export const SKILLS: TSkill[] = [
  {
    name: 'JavaScript',
    icon: SiJavascript,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'TypeScript',
    icon: SiTypescript,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'React.js',
    icon: FaReact,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'React Native',
    icon: FaReact,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'Next.js',
    icon: TbBrandNextjs,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'Angular',
    icon: SiAngular,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'TailwindCSS',
    icon: SiTailwindcss,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'shadcn/ui',
    icon: SiShadcnui,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'Redux',
    icon: SiRedux,
    category: 'Frontend',
    category_es: 'Frontend',
  },
  {
    name: 'Node.js',
    icon: FaNodeJs,
    category: 'Backend',
    category_es: 'Backend',
  },
  {
    name: 'Nest.js',
    icon: SiNestjs,
    category: 'Backend',
    category_es: 'Backend',
  },
  {
    name: 'Python',
    icon: SiPython,
    category: 'Backend',
    category_es: 'Backend',
  },
  {
    name: 'C',
    icon: SiC,
    category: 'Backend',
    category_es: 'Backend',
  },
  {
    name: 'Java',
    icon: FaJava,
    category: 'Backend',
    category_es: 'Backend',
  },
  {
    name: 'Spring Boot',
    icon: SiSpringboot,
    category: 'Backend',
    category_es: 'Backend',
  },
  {
    name: 'Prisma ORM',
    icon: SiPrisma,
    category: 'Database',
    category_es: 'Bases de datos',
  },
  {
    name: 'MySQL',
    icon: SiMysql,
    category: 'Database',
    category_es: 'Bases de datos',
  },
  {
    name: 'PostgreSQL',
    icon: SiPostgresql,
    category: 'Database',
    category_es: 'Bases de datos',
  },
  {
    name: 'MongoDB',
    icon: SiMongodb,
    category: 'Database',
    category_es: 'Bases de datos',
  },
  {
    name: 'Postman',
    icon: SiPostman,
    category: 'Backend',
    category_es: 'Backend',
  },
  {
    name: 'AWS',
    icon: FaAws,
    category: 'Infrastructure',
    category_es: 'Infraestructura',
  },
  {
    name: 'Azure',
    icon: SiMicrosoftazure,
    category: 'Infrastructure',
    category_es: 'Infraestructura',
  },
  {
    name: 'DigitalOcean',
    icon: FaDigitalOcean,
    category: 'Infrastructure',
    category_es: 'Infraestructura',
  },
  {
    name: 'NGINX',
    icon: SiNginx,
    category: 'DevOps',
    category_es: 'DevOps',
  },
  {
    name: 'Git',
    icon: BsGit,
    category: 'Control',
    category_es: 'Control',
  },
  {
    name: 'GitHub',
    icon: FaGithub,
    category: 'Control',
    category_es: 'Control',
  },
  {
    name: 'Docker',
    icon: FaDocker,
    category: 'DevOps',
    category_es: 'DevOps',
  },
  {
    name: 'Linux',
    icon: SiLinux,
    category: 'DevOps',
    category_es: 'DevOps',
  },
  {
    name: 'Figma',
    icon: SiFigma,
    category: 'Design',
    category_es: 'Diseño',
  },
  {
    name: 'Illustrator',
    icon: SiAdobeillustrator,
    category: 'Design',
    category_es: 'Diseño',
  },
];
